In [1]:
import numpy as np

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable
import torch.optim as optim
from torchvision import datasets, transforms

import matplotlib

import matplotlib.pyplot as plt

import os
import random
import math

from torch.utils.data.dataset import Dataset

INPUT_PATH = "./output/nodule_npy/"

In [2]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
BATCH_SIZE = 20
nz = 100
n_epochs = 500
ngf = 64
ngpu = 1
print(device)

cuda:0


In [3]:
def weights_init(m):
    classname = m.__class__.__name__
    if classname.find('Conv') != -1:
        m.weight.data.normal_(0.0, 0.02)
    elif classname.find('BatchNorm') != -1:
        m.weight.data.normal_(1.0, 0.02)
        m.bias.data.fill_(0)

def chunks(arr, m):
    nchunk = int(math.ceil(len(arr) / float(m)))
    return [arr[i:i + nchunk] for i in range(0, len(arr), nchunk)]

def five_folder(arr, number):
    training_set = []
    test_set = []
    for j in range(len(arr)):
        if number == j:
            test_set.extend(arr[j])
        else:
            training_set.extend(arr[j])
    return training_set, test_set


class MyDataset(Dataset):
    def __init__(self, images):
        self.images = images

    def __getitem__(self, index):#返回的是tensor
        img = self.images[index]
        return img

    def __len__(self):
        return len(self.images)

In [4]:
# Generator
class Generator(nn.Module):
    def __init__(self, ngpu):
        super(Generator, self).__init__()
        self.ngpu = ngpu

        self.project = nn.Sequential(
          nn.Linear(nz, 1 * 5 * 5 * ngf * 4, bias=False)
        )
        self.deconv = nn.Sequential(
          # input is Z, going into a deconvolution
          # state size. BATCH_SIZE x (ngf*8) x 4 x 4 x 4
#           nn.ConvTranspose3d(ngf * 8, ngf * 4, kernel_size=4, stride=2, padding=1, bias=False),
#           nn.BatchNorm3d(ngf * 4),
#           nn.ReLU(True),
          # state size. BATCH_SIZE x (ngf*4) x 1 x 5 x 5
          nn.ConvTranspose3d(ngf * 4, ngf * 2, kernel_size=4, stride=2, padding=1, bias=False),
          nn.BatchNorm3d(ngf * 2),
          nn.ReLU(True),
          # state size. BATCH_SIZE x (ngf*2) x 2 x 10 x 10
          nn.ConvTranspose3d(ngf * 2, ngf, kernel_size=4, stride=2, padding=1, bias=False),
          nn.BatchNorm3d(ngf),
          nn.ReLU(True),
          # state size. BATCH_SIZE x (ngf) x 4 x 20 x 20
          nn.ConvTranspose3d(ngf, 1, kernel_size=4, stride=2, padding=1, bias=False),
          nn.Tanh()
          # state size. BATCH_SIZE x 1 x 8 x 40 x 40
        )

    def forward(self, input):
        x = self.project(input)
        # Conv3d的规定输入数据格式为(batch, channel, Depth, Height, Width)
#         print(x.shape)
        x = x.view(-1, ngf * 4, 1, 5, 5)
#         x = self.deconv(x)
        
        if input.is_cuda and self.ngpu > 1:
            output = nn.parallel.data_parallel(self.deconv, x, range(self.ngpu))
        else:
            output = self.deconv(x)

        return output


# Discriminator
def softmax(input, dim=1):
    transposed_input = input.transpose(dim, len(input.size()) - 1)
    softmaxed_output = F.softmax(transposed_input.contiguous().view(-1, transposed_input.size(-1)), dim=-1)
    return softmaxed_output.view(*transposed_input.size()).transpose(dim, len(input.size()) - 1)

class ConvLayer(nn.Module):
    def __init__(self, in_channels=1, out_channels=256, kernel_size=(2,9,9)):
        super(ConvLayer, self).__init__()

        self.conv = nn.Conv3d(in_channels=in_channels,
                                out_channels=out_channels,
                                kernel_size=kernel_size,
                                stride=1
                              )

    def forward(self, x):
        return F.relu(self.conv(x))


class PrimaryCaps(nn.Module):
    def __init__(self, num_capsules=8, in_channels=256, out_channels=32, kernel_size=(2,9,9), num_routes=32 * 12 * 12 * 6):
        super(PrimaryCaps, self).__init__()

        self.capsules = nn.ModuleList([
          nn.Conv3d(in_channels=in_channels, out_channels=out_channels, kernel_size=kernel_size, stride=(1,2,2), padding=0) 
                      for _ in range(num_capsules)])
  
    def forward(self, x):
        u = [capsule(x).view(x.size(0), -1, 1) for capsule in self.capsules]
        u = torch.cat(u, dim=-1)
        return self.squash(u)
  
    def squash(self, input_tensor):
        squared_norm = (input_tensor ** 2).sum(-1, keepdim=True)
        output_tensor = squared_norm *  input_tensor / ((1. + squared_norm) * torch.sqrt(squared_norm))
        return output_tensor



class DigitCaps(nn.Module):
    def __init__(self, num_capsules=1, num_routes=32 * 12 * 12 * 6, in_channels=8, out_channels=16, num_iterations=3):
        super(DigitCaps, self).__init__()

        self.in_channels = in_channels
        self.num_routes = num_routes
        self.num_capsules = num_capsules
        self.num_iterations = num_iterations
        self.route_weights = nn.Parameter(torch.randn(num_capsules, num_routes, in_channels, out_channels)).to(device)

    def forward(self, x):
        # 矩阵相乘
        # x.size(): [1, batch_size, in_capsules, 1, dim_in_capsule]
        # weight.size(): [num_capsules, 1, num_route, in_channels, out_channels]
        priors = x[None, :, :, None, :] @ self.route_weights[:, None, :, :, :]
        logits = Variable(torch.zeros(*priors.size())).to(device)

        for i in range(self.num_iterations):
            probs = softmax(logits, dim=2)
            outputs = self.squash((probs * priors).sum(dim=2, keepdim=True))

            if i != self.num_routes - 1:
                delta_logits = (priors * outputs).sum(dim=-1, keepdim=True)
                logits = logits + delta_logits
        
        return outputs.squeeze()
  
    def squash(self, input_tensor):
        squared_norm = (input_tensor ** 2).sum(-1, keepdim=True)
        output_tensor = squared_norm * input_tensor / ((1. + squared_norm) * torch.sqrt(squared_norm))
        return output_tensor


class Decoder(nn.Module):
    def __init__(self):
        super(Decoder, self).__init__()
    
        self.reconstraction_layers = nn.Sequential(
          nn.Linear(16 * 10, 512),
          nn.ReLU(inplace=True),
          nn.Linear(512, 1024),
          nn.ReLU(inplace=True),
          nn.Linear(1024, 784),
          nn.Sigmoid()
        )
      
    def forward(self, x, data):
        classes = (x ** 2).sum(dim=-1) ** 0.5
        classes = F.softmax(classes, dim=-1)

        _, max_length_indices = classes.max(dim=1)
        masked = Variable(torch.sparse.torch.eye(10))
        if USE_CUDA:
              masked = masked.cuda()
        masked = masked.index_select(dim=0, index=max_length_indices.squeeze(1).data)
    
        reconstructions = self.reconstraction_layers((x * masked[:, :, None, None]).view(x.size(0), -1))
        reconstructions = reconstructions.view(-1, 1, 28, 28)

        return reconstructions, masked


class CapsNet(nn.Module):
    def __init__(self, ngpu):
        super(CapsNet, self).__init__()
        self.ngpu = ngpu
        
        self.conv_layer = ConvLayer()
        self.primary_capsules = PrimaryCaps()
        self.digit_capsules = DigitCaps()

        # self.decoder = Decoder()
        # self.mse_loss = nn.MSELoss()
      
    def forward(self, data):
        if data.is_cuda and self.ngpu > 1:
            output = nn.parallel.data_parallel(self.conv_layer, data, range(self.ngpu))
            output = nn.parallel.data_parallel(self.primary_capsules, output, range(self.ngpu))
            output = nn.parallel.data_parallel(self.digit_capsules, output, range(self.ngpu))
        else:
            output = self.digit_capsules(self.primary_capsules(self.conv_layer(data)))

        classes = (output ** 2).sum(dim=-1) ** 0.5        
        return classes, output

        #reconstructions, masked = self.decoder(output, data)
        #return output, reconstructions, masked

    # def loss(self, data, x, target, reconstructions):
      #   return self.margin_loss(x, target) + self.reconstruction_loss(data, reconstructions)

    # def margin_loss(self, x, labels, size_average=True):
      #   batch_size = x.size(0)

      #   v_c = torch.sqrt((x**2).sum(dim=2, keepdim=True))

      #   left = F.relu(0.9 - v_c).view(batch_size, -1)
      #   right = F.relu(v_c - 0.1).view(batch_size, -1)

      #   loss = labels * left + 0.5 * (1.0 - labels) * right
      #   loss = loss.sum(dim=1).mean()

      #   return loss

    # def reconstruction_loss(self, data, reconstructions):
      #   loss = self.mse_loss(reconstructions.view(reconstructions.size(0), -1), data.view(reconstructions.size(0), -1))
      #   return loss * 0.0005


class CapsuleLoss(nn.Module):
    def __init__(self):
        super(CapsuleLoss, self).__init__()

    def forward(self, classes, labels):
        left = F.relu(0.9 - classes, inplace=True) ** 2
        right = F.relu(classes - 0.1, inplace=True) ** 2

        margin_loss = labels * left + 0.5 * (1. - labels) * right
        margin_loss = margin_loss.sum()

        return margin_loss / classes.size(0)

In [5]:
accuracy_list = []

def train(cross_part, train_loader, single_test_set):
    netD = CapsNet(ngpu).to(device)
    criterion = CapsuleLoss()

    netG = Generator(ngpu).to(device)
    netG.apply(weights_init)

    fixed_noise = torch.randn(BATCH_SIZE, nz, device=device)
    real_label = 1
    fake_label = 0

    optimizerD = optim.Adam(netD.parameters(), lr=0.0002, betas=(0.5, 0.999))
    optimizerG = optim.Adam(netG.parameters(), lr=0.0002, betas=(0.5, 0.999))
    
    test_loader = torch.utils.data.DataLoader(MyDataset(single_test_set), batch_size=BATCH_SIZE, shuffle=True)
    
    
    for epoch in range(n_epochs):
        print("-----THE [{}/{}] epoch start-----".format(epoch + 1, n_epochs))
        
        for j, data in enumerate(train_loader, 0):
#                     print(j, data.shape) #torch.Size([32, 1, 8, 40, 40])

#                     plt.figure()
#                     for lenc in range(data.shape[0]):
#                         for len_img in range(8):
#                             plt.subplot(2, 4, len_img + 1)
#                             pixel_array = data[lenc][0][len_img]
#                             print(pixel_array)
#                             plt.imshow(pixel_array, cmap="gray")
#                         plt.show()


#                     pixel_array = data[0][0][0][20]
#                     print(pixel_array)

#                     data = data / 255.0
#                     pixel_array = data[0][0][0][20]
#                     print(pixel_array)
            ############################
            # (1) Update D network: minimize Lm(D(x), T = 1) + Lm(D(G(z)), T = 0)
            ###########################
            # train with real
            
            netD.train()
            
            netD.zero_grad()
            real_cpu = data.to(device, dtype=torch.float)
            batch_size = real_cpu.size(0)
            label = torch.full((batch_size,), real_label, device=device)   

            classes_d_real, output_d_real = netD(real_cpu)
#                     print("ERR_D_REAL:",classes_d_real)
            errD_real = criterion(classes_d_real, label)
            errD_real.backward()
            D_x = output_d_real.mean().item()

            # train with fake
            noise = torch.randn(batch_size, nz, device=device)
            fake = netG(noise)
            label.fill_(fake_label)
            classes_d_fake, output_d_fake = netD(fake.detach())

#                     print("ERR_D_FAKE:",classes_d_fake)
            errD_fake = criterion(classes_d_fake, label)
            errD_fake.backward()
            D_G_z1 = output_d_fake.mean().item()
            errD = errD_real + errD_fake
            optimizerD.step()

            ############################
            # (2) Update G network: minimize Lm(D(G(z)), T=1)
            ###########################
            netG.zero_grad()
            label.fill_(real_label)
            netD.eval()

            classes_g, output_g = netD(fake)
#                     print("ERRG:",classes_g)

            if epoch % 5 == 0:
                print(classes_g)
            errG = criterion(classes_g, label)
            errG.backward()
            D_G_z2 = output_g.mean().item()
            optimizerG.step()

#                     print("The batch data shape is {}".format(data.shape))

            print('[%d/%d] Loss_D: %.4f Loss_G: %.4f D(x): %.4f D(G(z)): %.4f / %.4f'
                  % (j + 1, len(train_loader), errD.item(), errG.item(), D_x, D_G_z1, D_G_z2))


        print("-----THE [{}/{}] epoch end-----".format(epoch + 1, n_epochs))
        
       
    
    return test_sum
    

In [6]:
input_data = os.listdir(INPUT_PATH)
flag = 1

for radiologist in input_data: #遍历patient文件夹——study指代每一个study文件夹
    if flag != 1:
        break
    flag += 1
    if not radiologist.startswith('.'): #忽略.DS文件        
        npy_file_path = os.path.join(INPUT_PATH, radiologist)
        npy_files = os.listdir(npy_file_path)
        npy_list = []
        for i in npy_files:
            npy_path = os.path.join(npy_file_path, i)
            single_npy = np.load(npy_path)
            single_fliplr_npy = np.fliplr(single_npy)
#             single_npy = (single_npy - np.average(single_npy)) / np.std(single_npy)
#             single_fliplr_npy = (single_fliplr_npy - np.average(single_fliplr_npy)) / np.std(single_fliplr_npy)
            single_npy = (single_npy - 127.5) / 127.5
            single_fliplr_npy = (single_fliplr_npy - 127.5) / 127.5
            #print(single_npy.shape)
            npy_list.append(single_fliplr_npy)
            npy_list.append(single_npy)

#         print(npy_file_path, np.array(npy_list).shape)
        random.shuffle(npy_list)
        npy_chunks = chunks(npy_list, 5)

#         print("THIS IS the data from {}. AND NOW the 5-folder cross-valiation start:".format(npy_file_path))   
   
#         for i in range(5):
            #training
#             print("-------------THE {} part(as the test set) cross-valiation start----------------------".format(i + 1))
        
        print("THIS IS the data from {}. AND NOW the training STARTS:".format(npy_file_path))
        single_training_set, single_test_set = five_folder(npy_chunks, 4)
        train_loader = torch.utils.data.DataLoader(MyDataset(single_training_set), batch_size=BATCH_SIZE, shuffle=True)

        #print(len(train_loader), type(train_loader))
        single_test_acc = train(i, train_loader,single_test_set)


THIS IS the data from ./output/nodule_npy/Radiologist_1. AND NOW the training STARTS:
-----THE [1/500] epoch start-----
tensor([0.0032, 0.0031, 0.0030, 0.0033, 0.0028, 0.0034, 0.0035, 0.0035, 0.0036,
        0.0031, 0.0036, 0.0037, 0.0033, 0.0032, 0.0032, 0.0031, 0.0033, 0.0033,
        0.0033, 0.0031], device='cuda:0', grad_fn=<PowBackward0>)
[1/32] Loss_D: 0.8100 Loss_G: 0.8041 D(x): 0.0000 D(G(z)): -0.0000 / 0.0002
tensor([0.0084, 0.0086, 0.0081, 0.0088, 0.0090, 0.0094, 0.0089, 0.0085, 0.0079,
        0.0083, 0.0090, 0.0091, 0.0082, 0.0084, 0.0083, 0.0090, 0.0080, 0.0083,
        0.0086, 0.0084], device='cuda:0', grad_fn=<PowBackward0>)
[2/32] Loss_D: 0.7885 Loss_G: 0.7947 D(x): 0.0008 D(G(z)): 0.0002 / 0.0006
tensor([0.0112, 0.0117, 0.0113, 0.0119, 0.0118, 0.0109, 0.0111, 0.0110, 0.0110,
        0.0111, 0.0114, 0.0114, 0.0112, 0.0113, 0.0114, 0.0108, 0.0120, 0.0116,
        0.0106, 0.0110], device='cuda:0', grad_fn=<PowBackward0>)
[3/32] Loss_D: 0.7714 Loss_G: 0.7898 D(x): 0.0016 D

tensor([0.1118, 0.1329, 0.0121, 0.1182, 0.1802, 0.1453, 0.0854, 0.0423, 0.0570,
        0.1619, 0.1274, 0.1273, 0.0998, 0.1546, 0.0695, 0.0604, 0.0389, 0.1512,
        0.0447, 0.0448], device='cuda:0', grad_fn=<PowBackward0>)
[28/32] Loss_D: 0.6260 Loss_G: 0.6451 D(x): 0.0068 D(G(z)): 0.0074 / 0.0063
tensor([0.1358, 0.1217, 0.1009, 0.0457, 0.1044, 0.2136, 0.1728, 0.1402, 0.1734,
        0.1495, 0.1410, 0.1364, 0.1070, 0.1896, 0.0939, 0.2139, 0.2016, 0.2107,
        0.0682, 0.1438], device='cuda:0', grad_fn=<PowBackward0>)
[29/32] Loss_D: 0.6359 Loss_G: 0.5750 D(x): 0.0067 D(G(z)): 0.0084 / 0.0090
tensor([0.2080, 0.0825, 0.0913, 0.1974, 0.2056, 0.2449, 0.1225, 0.1497, 0.2380,
        0.2679, 0.1762, 0.2547, 0.1850, 0.1053, 0.2241, 0.1602, 0.0974, 0.1460,
        0.2275, 0.0602], device='cuda:0', grad_fn=<PowBackward0>)
[30/32] Loss_D: 0.5995 Loss_G: 0.5334 D(x): 0.0084 D(G(z)): 0.0106 / 0.0108
tensor([0.0913, 0.1997, 0.1576, 0.2334, 0.2395, 0.2362, 0.1714, 0.2755, 0.2030,
        0.2114

[25/32] Loss_D: 0.5732 Loss_G: 0.3145 D(x): 0.0093 D(G(z)): 0.0185 / 0.0183
[26/32] Loss_D: 0.5936 Loss_G: 0.3298 D(x): 0.0095 D(G(z)): 0.0182 / 0.0171
[27/32] Loss_D: 0.5779 Loss_G: 0.3362 D(x): 0.0097 D(G(z)): 0.0170 / 0.0170
[28/32] Loss_D: 0.4964 Loss_G: 0.3306 D(x): 0.0136 D(G(z)): 0.0168 / 0.0166
[29/32] Loss_D: 0.5840 Loss_G: 0.3370 D(x): 0.0092 D(G(z)): 0.0168 / 0.0166
[30/32] Loss_D: 0.5456 Loss_G: 0.3407 D(x): 0.0108 D(G(z)): 0.0167 / 0.0165
[31/32] Loss_D: 0.4699 Loss_G: 0.3309 D(x): 0.0143 D(G(z)): 0.0168 / 0.0170
[32/32] Loss_D: 0.3741 Loss_G: 0.3183 D(x): 0.0184 D(G(z)): 0.0175 / 0.0183
-----THE [4/500] epoch end-----
-----THE [5/500] epoch start-----
[1/32] Loss_D: 0.5401 Loss_G: 0.3218 D(x): 0.0117 D(G(z)): 0.0188 / 0.0180
[2/32] Loss_D: 0.5277 Loss_G: 0.3140 D(x): 0.0122 D(G(z)): 0.0193 / 0.0192
[3/32] Loss_D: 0.5075 Loss_G: 0.3062 D(x): 0.0130 D(G(z)): 0.0206 / 0.0201
[4/32] Loss_D: 0.5308 Loss_G: 0.2965 D(x): 0.0127 D(G(z)): 0.0225 / 0.0218
[5/32] Loss_D: 0.4900 Loss

[17/32] Loss_D: 0.5502 Loss_G: 0.2804 D(x): 0.0107 D(G(z)): 0.0223 / 0.0222
tensor([0.3786, 0.3698, 0.3657, 0.3680, 0.3653, 0.3773, 0.3720, 0.3807, 0.3767,
        0.3681, 0.3623, 0.3595, 0.3752, 0.3719, 0.3786, 0.3685, 0.3679, 0.3666,
        0.3625, 0.3684], device='cuda:0', grad_fn=<PowBackward0>)
[18/32] Loss_D: 0.5081 Loss_G: 0.2807 D(x): 0.0129 D(G(z)): 0.0220 / 0.0219
tensor([0.3739, 0.3667, 0.3692, 0.3808, 0.3702, 0.3727, 0.3836, 0.3738, 0.3780,
        0.3692, 0.3761, 0.3818, 0.3802, 0.3819, 0.3772, 0.3799, 0.3686, 0.3717,
        0.3624, 0.3767], device='cuda:0', grad_fn=<PowBackward0>)
[19/32] Loss_D: 0.4948 Loss_G: 0.2759 D(x): 0.0133 D(G(z)): 0.0220 / 0.0223
tensor([0.3831, 0.3691, 0.3828, 0.3781, 0.3768, 0.3842, 0.3685, 0.3812, 0.3808,
        0.3787, 0.3798, 0.3736, 0.3767, 0.3822, 0.3786, 0.3730, 0.3642, 0.3740,
        0.3783, 0.3797], device='cuda:0', grad_fn=<PowBackward0>)
[20/32] Loss_D: 0.5082 Loss_G: 0.2734 D(x): 0.0124 D(G(z)): 0.0222 / 0.0223
tensor([0.3769, 0.

[17/32] Loss_D: 0.4910 Loss_G: 0.2519 D(x): 0.0134 D(G(z)): 0.0245 / 0.0245
[18/32] Loss_D: 0.4595 Loss_G: 0.2660 D(x): 0.0157 D(G(z)): 0.0245 / 0.0234
[19/32] Loss_D: 0.5314 Loss_G: 0.2621 D(x): 0.0116 D(G(z)): 0.0236 / 0.0234
[20/32] Loss_D: 0.5378 Loss_G: 0.2643 D(x): 0.0123 D(G(z)): 0.0236 / 0.0242
[21/32] Loss_D: 0.5405 Loss_G: 0.2694 D(x): 0.0115 D(G(z)): 0.0241 / 0.0239
[22/32] Loss_D: 0.5039 Loss_G: 0.2657 D(x): 0.0126 D(G(z)): 0.0241 / 0.0239
[23/32] Loss_D: 0.5542 Loss_G: 0.2728 D(x): 0.0107 D(G(z)): 0.0237 / 0.0228
[24/32] Loss_D: 0.4562 Loss_G: 0.2701 D(x): 0.0146 D(G(z)): 0.0229 / 0.0231
[25/32] Loss_D: 0.5271 Loss_G: 0.2718 D(x): 0.0120 D(G(z)): 0.0231 / 0.0232
[26/32] Loss_D: 0.5101 Loss_G: 0.2669 D(x): 0.0130 D(G(z)): 0.0229 / 0.0232
[27/32] Loss_D: 0.5782 Loss_G: 0.2789 D(x): 0.0098 D(G(z)): 0.0235 / 0.0228
[28/32] Loss_D: 0.4998 Loss_G: 0.2784 D(x): 0.0124 D(G(z)): 0.0230 / 0.0228
[29/32] Loss_D: 0.5269 Loss_G: 0.2711 D(x): 0.0128 D(G(z)): 0.0229 / 0.0231
[30/32] Loss

[7/32] Loss_D: 0.4856 Loss_G: 0.2582 D(x): 0.0143 D(G(z)): 0.0247 / 0.0247
tensor([0.4019, 0.3941, 0.4005, 0.3869, 0.4046, 0.3978, 0.4037, 0.3956, 0.3876,
        0.3941, 0.3916, 0.4010, 0.3950, 0.3902, 0.4053, 0.3876, 0.3878, 0.3958,
        0.3921, 0.3961], device='cuda:0', grad_fn=<PowBackward0>)
[8/32] Loss_D: 0.5094 Loss_G: 0.2546 D(x): 0.0129 D(G(z)): 0.0249 / 0.0248
tensor([0.4076, 0.4052, 0.3953, 0.3992, 0.4067, 0.3973, 0.4060, 0.3975, 0.3991,
        0.4035, 0.3988, 0.4099, 0.4014, 0.4060, 0.4019, 0.4090, 0.4072, 0.4041,
        0.4102, 0.4033], device='cuda:0', grad_fn=<PowBackward0>)
[9/32] Loss_D: 0.4784 Loss_G: 0.2466 D(x): 0.0144 D(G(z)): 0.0250 / 0.0249
tensor([0.3984, 0.4078, 0.4045, 0.4005, 0.3995, 0.4060, 0.3998, 0.4037, 0.4042,
        0.3886, 0.4020, 0.3937, 0.3947, 0.3982, 0.4028, 0.4033, 0.4006, 0.4056,
        0.3967, 0.4019], device='cuda:0', grad_fn=<PowBackward0>)
[10/32] Loss_D: 0.5718 Loss_G: 0.2494 D(x): 0.0110 D(G(z)): 0.0247 / 0.0245
tensor([0.4006, 0.405

[10/32] Loss_D: 0.4632 Loss_G: 0.3188 D(x): 0.0145 D(G(z)): 0.0175 / 0.0171
[11/32] Loss_D: 0.5038 Loss_G: 0.3094 D(x): 0.0136 D(G(z)): 0.0188 / 0.0182
[12/32] Loss_D: 0.4781 Loss_G: 0.2761 D(x): 0.0132 D(G(z)): 0.0216 / 0.0213
[13/32] Loss_D: 0.4835 Loss_G: 0.2311 D(x): 0.0147 D(G(z)): 0.0260 / 0.0252
[14/32] Loss_D: 0.4817 Loss_G: 0.2087 D(x): 0.0150 D(G(z)): 0.0288 / 0.0279
[15/32] Loss_D: 0.4709 Loss_G: 0.1996 D(x): 0.0159 D(G(z)): 0.0299 / 0.0293
[16/32] Loss_D: 0.4434 Loss_G: 0.1926 D(x): 0.0174 D(G(z)): 0.0299 / 0.0297
[17/32] Loss_D: 0.5611 Loss_G: 0.2012 D(x): 0.0126 D(G(z)): 0.0306 / 0.0297
[18/32] Loss_D: 0.4335 Loss_G: 0.1887 D(x): 0.0188 D(G(z)): 0.0303 / 0.0302
[19/32] Loss_D: 0.5135 Loss_G: 0.1888 D(x): 0.0146 D(G(z)): 0.0307 / 0.0302
[20/32] Loss_D: 0.4846 Loss_G: 0.2004 D(x): 0.0149 D(G(z)): 0.0302 / 0.0295
[21/32] Loss_D: 0.5584 Loss_G: 0.2177 D(x): 0.0115 D(G(z)): 0.0298 / 0.0281
[22/32] Loss_D: 0.6046 Loss_G: 0.2444 D(x): 0.0096 D(G(z)): 0.0282 / 0.0264
[23/32] Loss

[20/32] Loss_D: 0.5118 Loss_G: 0.2701 D(x): 0.0133 D(G(z)): 0.0208 / 0.0206
[21/32] Loss_D: 0.5729 Loss_G: 0.2764 D(x): 0.0099 D(G(z)): 0.0206 / 0.0200
[22/32] Loss_D: 0.4965 Loss_G: 0.2820 D(x): 0.0141 D(G(z)): 0.0203 / 0.0196
[23/32] Loss_D: 0.5058 Loss_G: 0.2810 D(x): 0.0119 D(G(z)): 0.0197 / 0.0195
[24/32] Loss_D: 0.4822 Loss_G: 0.2820 D(x): 0.0129 D(G(z)): 0.0193 / 0.0191
[25/32] Loss_D: 0.4055 Loss_G: 0.2763 D(x): 0.0156 D(G(z)): 0.0192 / 0.0193
[26/32] Loss_D: 0.4331 Loss_G: 0.2820 D(x): 0.0159 D(G(z)): 0.0191 / 0.0185
[27/32] Loss_D: 0.3922 Loss_G: 0.2900 D(x): 0.0175 D(G(z)): 0.0186 / 0.0187
[28/32] Loss_D: 0.4931 Loss_G: 0.3016 D(x): 0.0145 D(G(z)): 0.0187 / 0.0177
[29/32] Loss_D: 0.4561 Loss_G: 0.3168 D(x): 0.0162 D(G(z)): 0.0178 / 0.0170
[30/32] Loss_D: 0.5250 Loss_G: 0.3226 D(x): 0.0110 D(G(z)): 0.0171 / 0.0167
[31/32] Loss_D: 0.5303 Loss_G: 0.3347 D(x): 0.0120 D(G(z)): 0.0168 / 0.0162
[32/32] Loss_D: 0.3950 Loss_G: 0.3490 D(x): 0.0194 D(G(z)): 0.0164 / 0.0155
-----THE [15

[24/32] Loss_D: 0.4960 Loss_G: 0.2612 D(x): 0.0131 D(G(z)): 0.0236 / 0.0239
tensor([0.3722, 0.4036, 0.3932, 0.3849, 0.3910, 0.4048, 0.4118, 0.4116, 0.3784,
        0.3869, 0.3841, 0.3933, 0.3838, 0.3891, 0.3931, 0.3973, 0.3765, 0.3761,
        0.4132, 0.3942], device='cuda:0', grad_fn=<PowBackward0>)
[25/32] Loss_D: 0.5168 Loss_G: 0.2582 D(x): 0.0122 D(G(z)): 0.0238 / 0.0236
tensor([0.3859, 0.3987, 0.4086, 0.3812, 0.4071, 0.3799, 0.3810, 0.3922, 0.3835,
        0.3879, 0.3854, 0.3985, 0.4066, 0.3799, 0.4125, 0.3909, 0.3795, 0.3826,
        0.3908, 0.3757], device='cuda:0', grad_fn=<PowBackward0>)
[26/32] Loss_D: 0.5400 Loss_G: 0.2598 D(x): 0.0112 D(G(z)): 0.0236 / 0.0233
tensor([0.3998, 0.3999, 0.4098, 0.3930, 0.3828, 0.3831, 0.3902, 0.3882, 0.3732,
        0.3978, 0.3810, 0.3703, 0.3880, 0.3951, 0.4065, 0.3715, 0.3821, 0.3934,
        0.3841, 0.3799], device='cuda:0', grad_fn=<PowBackward0>)
[27/32] Loss_D: 0.5342 Loss_G: 0.2618 D(x): 0.0117 D(G(z)): 0.0233 / 0.0229
tensor([0.4032, 0.

[12/32] Loss_D: 0.5148 Loss_G: 0.2422 D(x): 0.0124 D(G(z)): 0.0236 / 0.0231
[13/32] Loss_D: 0.4085 Loss_G: 0.2325 D(x): 0.0167 D(G(z)): 0.0231 / 0.0233
[14/32] Loss_D: 0.4879 Loss_G: 0.2337 D(x): 0.0136 D(G(z)): 0.0235 / 0.0232
[15/32] Loss_D: 0.4770 Loss_G: 0.2415 D(x): 0.0136 D(G(z)): 0.0232 / 0.0225
[16/32] Loss_D: 0.5169 Loss_G: 0.2467 D(x): 0.0125 D(G(z)): 0.0224 / 0.0218
[17/32] Loss_D: 0.4264 Loss_G: 0.2447 D(x): 0.0165 D(G(z)): 0.0220 / 0.0222
[18/32] Loss_D: 0.3933 Loss_G: 0.2400 D(x): 0.0187 D(G(z)): 0.0224 / 0.0229
[19/32] Loss_D: 0.5193 Loss_G: 0.2427 D(x): 0.0129 D(G(z)): 0.0230 / 0.0227
[20/32] Loss_D: 0.5167 Loss_G: 0.2495 D(x): 0.0126 D(G(z)): 0.0226 / 0.0219
[21/32] Loss_D: 0.5450 Loss_G: 0.2576 D(x): 0.0113 D(G(z)): 0.0220 / 0.0211
[22/32] Loss_D: 0.4794 Loss_G: 0.2556 D(x): 0.0138 D(G(z)): 0.0213 / 0.0212
[23/32] Loss_D: 0.4998 Loss_G: 0.2583 D(x): 0.0134 D(G(z)): 0.0221 / 0.0215
[24/32] Loss_D: 0.4529 Loss_G: 0.2622 D(x): 0.0152 D(G(z)): 0.0218 / 0.0217
[25/32] Loss

[14/32] Loss_D: 0.4294 Loss_G: 0.2377 D(x): 0.0173 D(G(z)): 0.0230 / 0.0233
tensor([0.4250, 0.3967, 0.4787, 0.3876, 0.3767, 0.3829, 0.4259, 0.4655, 0.3964,
        0.3957, 0.3871, 0.3942, 0.4156, 0.4102, 0.4061, 0.3925, 0.4168, 0.3805,
        0.3906, 0.4344], device='cuda:0', grad_fn=<PowBackward0>)
[15/32] Loss_D: 0.4959 Loss_G: 0.2428 D(x): 0.0132 D(G(z)): 0.0243 / 0.0236
tensor([0.3878, 0.4286, 0.4133, 0.3917, 0.3864, 0.3786, 0.4262, 0.4560, 0.4765,
        0.4166, 0.3853, 0.4102, 0.3907, 0.3890, 0.4255, 0.3808, 0.3851, 0.4423,
        0.4083, 0.3976], device='cuda:0', grad_fn=<PowBackward0>)
[16/32] Loss_D: 0.3732 Loss_G: 0.2419 D(x): 0.0195 D(G(z)): 0.0235 / 0.0235
tensor([0.3769, 0.4698, 0.3914, 0.3907, 0.3854, 0.4694, 0.4698, 0.3845, 0.3959,
        0.3827, 0.3823, 0.3783, 0.3763, 0.4341, 0.3892, 0.3821, 0.4136, 0.3779,
        0.3808, 0.4127], device='cuda:0', grad_fn=<PowBackward0>)
[17/32] Loss_D: 0.4905 Loss_G: 0.2488 D(x): 0.0135 D(G(z)): 0.0234 / 0.0230
tensor([0.2587, 0.

[5/32] Loss_D: 0.5019 Loss_G: 0.2188 D(x): 0.0137 D(G(z)): 0.0247 / 0.0244
[6/32] Loss_D: 0.4934 Loss_G: 0.2235 D(x): 0.0135 D(G(z)): 0.0246 / 0.0244
[7/32] Loss_D: 0.5230 Loss_G: 0.2269 D(x): 0.0125 D(G(z)): 0.0233 / 0.0232
[8/32] Loss_D: 0.3703 Loss_G: 0.2123 D(x): 0.0207 D(G(z)): 0.0245 / 0.0254
[9/32] Loss_D: 0.4625 Loss_G: 0.2066 D(x): 0.0160 D(G(z)): 0.0259 / 0.0257
[10/32] Loss_D: 0.5304 Loss_G: 0.2265 D(x): 0.0129 D(G(z)): 0.0244 / 0.0239
[11/32] Loss_D: 0.4875 Loss_G: 0.2205 D(x): 0.0144 D(G(z)): 0.0243 / 0.0240
[12/32] Loss_D: 0.4901 Loss_G: 0.2076 D(x): 0.0140 D(G(z)): 0.0253 / 0.0254
[13/32] Loss_D: 0.4940 Loss_G: 0.2151 D(x): 0.0142 D(G(z)): 0.0243 / 0.0241
[14/32] Loss_D: 0.4894 Loss_G: 0.2094 D(x): 0.0141 D(G(z)): 0.0252 / 0.0250
[15/32] Loss_D: 0.4425 Loss_G: 0.2063 D(x): 0.0167 D(G(z)): 0.0256 / 0.0259
[16/32] Loss_D: 0.5167 Loss_G: 0.2073 D(x): 0.0152 D(G(z)): 0.0257 / 0.0257
[17/32] Loss_D: 0.4168 Loss_G: 0.2106 D(x): 0.0172 D(G(z)): 0.0248 / 0.0251
[18/32] Loss_D: 0

[4/32] Loss_D: 0.4422 Loss_G: 0.2131 D(x): 0.0172 D(G(z)): 0.0256 / 0.0257
tensor([0.4270, 0.4833, 0.4179, 0.4383, 0.4482, 0.4284, 0.4432, 0.4917, 0.4512,
        0.4506, 0.4493, 0.4391, 0.4340, 0.4171, 0.5027, 0.4460, 0.4524, 0.4960,
        0.4265, 0.4769], device='cuda:0', grad_fn=<PowBackward0>)
[5/32] Loss_D: 0.4173 Loss_G: 0.2023 D(x): 0.0187 D(G(z)): 0.0250 / 0.0252
tensor([0.4435, 0.4743, 0.4315, 0.4509, 0.4538, 0.4427, 0.5101, 0.4874, 0.4483,
        0.4834, 0.4482, 0.4946, 0.4443, 0.4995, 0.4396, 0.4786, 0.4484, 0.4381,
        0.4489, 0.4736], device='cuda:0', grad_fn=<PowBackward0>)
[6/32] Loss_D: 0.4550 Loss_G: 0.1924 D(x): 0.0164 D(G(z)): 0.0258 / 0.0260
tensor([0.4171, 0.4288, 0.4827, 0.4931, 0.4351, 0.5030, 0.4346, 0.5064, 0.5010,
        0.4432, 0.4885, 0.4211, 0.4940, 0.4356, 0.4417, 0.4385, 0.4355, 0.4304,
        0.4615, 0.5094], device='cuda:0', grad_fn=<PowBackward0>)
[7/32] Loss_D: 0.4585 Loss_G: 0.1946 D(x): 0.0177 D(G(z)): 0.0269 / 0.0267
tensor([0.4229, 0.4519

tensor([0.4188, 0.4301, 0.3988, 0.4358], device='cuda:0',
       grad_fn=<PowBackward0>)
[32/32] Loss_D: 0.5572 Loss_G: 0.2298 D(x): 0.0110 D(G(z)): 0.0247 / 0.0237
-----THE [26/500] epoch end-----
-----THE [27/500] epoch start-----
[1/32] Loss_D: 0.5159 Loss_G: 0.2201 D(x): 0.0134 D(G(z)): 0.0237 / 0.0240
[2/32] Loss_D: 0.4270 Loss_G: 0.2150 D(x): 0.0167 D(G(z)): 0.0240 / 0.0247
[3/32] Loss_D: 0.4599 Loss_G: 0.2079 D(x): 0.0142 D(G(z)): 0.0245 / 0.0244
[4/32] Loss_D: 0.4817 Loss_G: 0.2192 D(x): 0.0136 D(G(z)): 0.0251 / 0.0246
[5/32] Loss_D: 0.4663 Loss_G: 0.2156 D(x): 0.0142 D(G(z)): 0.0243 / 0.0242
[6/32] Loss_D: 0.4182 Loss_G: 0.2110 D(x): 0.0162 D(G(z)): 0.0241 / 0.0245
[7/32] Loss_D: 0.3868 Loss_G: 0.1930 D(x): 0.0198 D(G(z)): 0.0246 / 0.0251
[8/32] Loss_D: 0.4602 Loss_G: 0.2008 D(x): 0.0156 D(G(z)): 0.0251 / 0.0252
[9/32] Loss_D: 0.4070 Loss_G: 0.1946 D(x): 0.0189 D(G(z)): 0.0251 / 0.0252
[10/32] Loss_D: 0.4741 Loss_G: 0.1953 D(x): 0.0140 D(G(z)): 0.0255 / 0.0250
[11/32] Loss_D: 

[8/32] Loss_D: 0.3883 Loss_G: 0.1929 D(x): 0.0184 D(G(z)): 0.0261 / 0.0262
[9/32] Loss_D: 0.4634 Loss_G: 0.1928 D(x): 0.0151 D(G(z)): 0.0256 / 0.0251
[10/32] Loss_D: 0.4395 Loss_G: 0.1921 D(x): 0.0168 D(G(z)): 0.0254 / 0.0253
[11/32] Loss_D: 0.4387 Loss_G: 0.1973 D(x): 0.0166 D(G(z)): 0.0258 / 0.0260
[12/32] Loss_D: 0.4700 Loss_G: 0.1952 D(x): 0.0154 D(G(z)): 0.0253 / 0.0253
[13/32] Loss_D: 0.4964 Loss_G: 0.2046 D(x): 0.0151 D(G(z)): 0.0250 / 0.0244
[14/32] Loss_D: 0.5118 Loss_G: 0.2050 D(x): 0.0138 D(G(z)): 0.0260 / 0.0257
[15/32] Loss_D: 0.4223 Loss_G: 0.2044 D(x): 0.0162 D(G(z)): 0.0246 / 0.0249
[16/32] Loss_D: 0.4950 Loss_G: 0.1996 D(x): 0.0140 D(G(z)): 0.0261 / 0.0258
[17/32] Loss_D: 0.4520 Loss_G: 0.2022 D(x): 0.0160 D(G(z)): 0.0254 / 0.0253
[18/32] Loss_D: 0.4857 Loss_G: 0.2036 D(x): 0.0141 D(G(z)): 0.0256 / 0.0253
[19/32] Loss_D: 0.4668 Loss_G: 0.2048 D(x): 0.0144 D(G(z)): 0.0253 / 0.0250
[20/32] Loss_D: 0.4364 Loss_G: 0.2048 D(x): 0.0159 D(G(z)): 0.0253 / 0.0253
[21/32] Loss_D

[21/32] Loss_D: 0.4764 Loss_G: 0.2017 D(x): 0.0149 D(G(z)): 0.0255 / 0.0254
tensor([0.4469, 0.4479, 0.4652, 0.4605, 0.4754, 0.4516, 0.4776, 0.4588, 0.4495,
        0.4684, 0.4571, 0.4660, 0.4381, 0.4544, 0.4649, 0.4580, 0.4500, 0.4632,
        0.4648, 0.4611], device='cuda:0', grad_fn=<PowBackward0>)
[22/32] Loss_D: 0.4428 Loss_G: 0.1946 D(x): 0.0163 D(G(z)): 0.0248 / 0.0251
tensor([0.4702, 0.4699, 0.4721, 0.4726, 0.4305, 0.4489, 0.4541, 0.4650, 0.4472,
        0.4719, 0.4446, 0.4341, 0.4500, 0.4682, 0.4525, 0.4385, 0.4408, 0.4515,
        0.4714, 0.4513], device='cuda:0', grad_fn=<PowBackward0>)
[23/32] Loss_D: 0.4441 Loss_G: 0.1980 D(x): 0.0155 D(G(z)): 0.0257 / 0.0254
tensor([0.4487, 0.4549, 0.4768, 0.4597, 0.4348, 0.4482, 0.4690, 0.4458, 0.4502,
        0.4528, 0.4765, 0.4684, 0.4705, 0.4839, 0.4574, 0.4559, 0.4563, 0.4721,
        0.4718, 0.4697], device='cuda:0', grad_fn=<PowBackward0>)
[24/32] Loss_D: 0.3859 Loss_G: 0.1927 D(x): 0.0185 D(G(z)): 0.0254 / 0.0257
tensor([0.4850, 0.

[1/32] Loss_D: 0.3857 Loss_G: 0.1952 D(x): 0.0183 D(G(z)): 0.0255 / 0.0256
[2/32] Loss_D: 0.4004 Loss_G: 0.1970 D(x): 0.0175 D(G(z)): 0.0251 / 0.0249
[3/32] Loss_D: 0.4442 Loss_G: 0.1959 D(x): 0.0167 D(G(z)): 0.0255 / 0.0255
[4/32] Loss_D: 0.4780 Loss_G: 0.1985 D(x): 0.0144 D(G(z)): 0.0254 / 0.0252
[5/32] Loss_D: 0.4063 Loss_G: 0.1941 D(x): 0.0181 D(G(z)): 0.0258 / 0.0254
[6/32] Loss_D: 0.4621 Loss_G: 0.1921 D(x): 0.0161 D(G(z)): 0.0256 / 0.0256
[7/32] Loss_D: 0.5052 Loss_G: 0.1982 D(x): 0.0129 D(G(z)): 0.0264 / 0.0256
[8/32] Loss_D: 0.4973 Loss_G: 0.2023 D(x): 0.0139 D(G(z)): 0.0248 / 0.0249
[9/32] Loss_D: 0.4737 Loss_G: 0.2047 D(x): 0.0156 D(G(z)): 0.0241 / 0.0242
[10/32] Loss_D: 0.4211 Loss_G: 0.1983 D(x): 0.0170 D(G(z)): 0.0249 / 0.0250
[11/32] Loss_D: 0.4179 Loss_G: 0.2048 D(x): 0.0172 D(G(z)): 0.0246 / 0.0242
[12/32] Loss_D: 0.4553 Loss_G: 0.1949 D(x): 0.0150 D(G(z)): 0.0253 / 0.0254
[13/32] Loss_D: 0.5011 Loss_G: 0.2041 D(x): 0.0136 D(G(z)): 0.0259 / 0.0255
[14/32] Loss_D: 0.480

[11/32] Loss_D: 0.4646 Loss_G: 0.2059 D(x): 0.0155 D(G(z)): 0.0240 / 0.0240
tensor([0.4502, 0.4429, 0.4353, 0.4351, 0.4453, 0.4575, 0.4533, 0.4363, 0.4323,
        0.4482, 0.4518, 0.4534, 0.4557, 0.4432, 0.4367, 0.4420, 0.4299, 0.4338,
        0.4459, 0.4475], device='cuda:0', grad_fn=<PowBackward0>)
[12/32] Loss_D: 0.5034 Loss_G: 0.2082 D(x): 0.0130 D(G(z)): 0.0234 / 0.0231
tensor([0.4447, 0.4267, 0.4344, 0.4287, 0.4324, 0.4413, 0.4316, 0.4519, 0.4572,
        0.4348, 0.4655, 0.4381, 0.4298, 0.4455, 0.4693, 0.4341, 0.4535, 0.4359,
        0.4548, 0.4224], device='cuda:0', grad_fn=<PowBackward0>)
[13/32] Loss_D: 0.4625 Loss_G: 0.2103 D(x): 0.0146 D(G(z)): 0.0243 / 0.0239
tensor([0.4416, 0.4504, 0.4475, 0.4582, 0.4603, 0.4499, 0.4389, 0.4323, 0.4417,
        0.4440, 0.4399, 0.4230, 0.4182, 0.4370, 0.4471, 0.4421, 0.4268, 0.4418,
        0.4441, 0.4295], device='cuda:0', grad_fn=<PowBackward0>)
[14/32] Loss_D: 0.5319 Loss_G: 0.2110 D(x): 0.0114 D(G(z)): 0.0237 / 0.0234
tensor([0.4469, 0.

[26/32] Loss_D: 0.3952 Loss_G: 0.2038 D(x): 0.0183 D(G(z)): 0.0244 / 0.0247
[27/32] Loss_D: 0.4993 Loss_G: 0.2029 D(x): 0.0136 D(G(z)): 0.0260 / 0.0258
[28/32] Loss_D: 0.3350 Loss_G: 0.1953 D(x): 0.0212 D(G(z)): 0.0260 / 0.0262
[29/32] Loss_D: 0.4014 Loss_G: 0.1926 D(x): 0.0173 D(G(z)): 0.0265 / 0.0261
[30/32] Loss_D: 0.4934 Loss_G: 0.1925 D(x): 0.0140 D(G(z)): 0.0249 / 0.0247
[31/32] Loss_D: 0.4757 Loss_G: 0.1944 D(x): 0.0147 D(G(z)): 0.0260 / 0.0259
[32/32] Loss_D: 0.3661 Loss_G: 0.1956 D(x): 0.0172 D(G(z)): 0.0253 / 0.0251
-----THE [37/500] epoch end-----
-----THE [38/500] epoch start-----
[1/32] Loss_D: 0.4914 Loss_G: 0.1887 D(x): 0.0138 D(G(z)): 0.0250 / 0.0246
[2/32] Loss_D: 0.4546 Loss_G: 0.2015 D(x): 0.0155 D(G(z)): 0.0252 / 0.0250
[3/32] Loss_D: 0.4315 Loss_G: 0.1976 D(x): 0.0156 D(G(z)): 0.0249 / 0.0247
[4/32] Loss_D: 0.4514 Loss_G: 0.1955 D(x): 0.0166 D(G(z)): 0.0248 / 0.0254
[5/32] Loss_D: 0.4055 Loss_G: 0.1871 D(x): 0.0184 D(G(z)): 0.0246 / 0.0247
[6/32] Loss_D: 0.4836 Los

[1/32] Loss_D: 0.4593 Loss_G: 0.1886 D(x): 0.0141 D(G(z)): 0.0243 / 0.0241
tensor([0.4799, 0.4749, 0.4452, 0.4586, 0.4868, 0.4885, 0.4410, 0.4470, 0.4773,
        0.4737, 0.4765, 0.4519, 0.4872, 0.4714, 0.4387, 0.4707, 0.4931, 0.4820,
        0.4819, 0.4736], device='cuda:0', grad_fn=<PowBackward0>)
[2/32] Loss_D: 0.4312 Loss_G: 0.1852 D(x): 0.0148 D(G(z)): 0.0242 / 0.0246
tensor([0.4572, 0.4630, 0.4486, 0.4716, 0.4548, 0.4509, 0.4730, 0.4697, 0.4478,
        0.4451, 0.4544, 0.4833, 0.4788, 0.4776, 0.4577, 0.4485, 0.4670, 0.4742,
        0.4549, 0.4585], device='cuda:0', grad_fn=<PowBackward0>)
[3/32] Loss_D: 0.4175 Loss_G: 0.1921 D(x): 0.0178 D(G(z)): 0.0253 / 0.0255
tensor([0.4616, 0.4606, 0.4515, 0.4595, 0.4541, 0.4567, 0.4682, 0.4733, 0.4742,
        0.4790, 0.4808, 0.4648, 0.4713, 0.4541, 0.4679, 0.4602, 0.4639, 0.4797,
        0.4729, 0.4562], device='cuda:0', grad_fn=<PowBackward0>)
[4/32] Loss_D: 0.4516 Loss_G: 0.1889 D(x): 0.0164 D(G(z)): 0.0249 / 0.0246
tensor([0.4527, 0.4526

tensor([0.4486, 0.4736, 0.4542, 0.4547, 0.4710, 0.4741, 0.4850, 0.4593, 0.4765,
        0.4665, 0.4872, 0.4677, 0.4490, 0.4780, 0.4688, 0.4712, 0.4779, 0.4517,
        0.4809, 0.4497], device='cuda:0', grad_fn=<PowBackward0>)
[29/32] Loss_D: 0.4700 Loss_G: 0.1874 D(x): 0.0149 D(G(z)): 0.0246 / 0.0247
tensor([0.4634, 0.4455, 0.4552, 0.4747, 0.4455, 0.4430, 0.4725, 0.4718, 0.4575,
        0.4682, 0.4647, 0.4556, 0.4737, 0.4659, 0.4420, 0.4699, 0.4667, 0.4763,
        0.4429, 0.4662], device='cuda:0', grad_fn=<PowBackward0>)
[30/32] Loss_D: 0.4776 Loss_G: 0.1928 D(x): 0.0148 D(G(z)): 0.0248 / 0.0246
tensor([0.4404, 0.4689, 0.4564, 0.4426, 0.4341, 0.4505, 0.4453, 0.4459, 0.4574,
        0.4557, 0.4399, 0.4565, 0.4606, 0.4557, 0.4502, 0.4638, 0.4453, 0.4665,
        0.4504, 0.4624], device='cuda:0', grad_fn=<PowBackward0>)
[31/32] Loss_D: 0.4712 Loss_G: 0.2004 D(x): 0.0156 D(G(z)): 0.0250 / 0.0246
tensor([0.4003, 0.3764, 0.3789, 0.4409], device='cuda:0',
       grad_fn=<PowBackward0>)
[32/3

[29/32] Loss_D: 0.4974 Loss_G: 0.1954 D(x): 0.0134 D(G(z)): 0.0254 / 0.0249
[30/32] Loss_D: 0.4481 Loss_G: 0.1995 D(x): 0.0143 D(G(z)): 0.0244 / 0.0236
[31/32] Loss_D: 0.3550 Loss_G: 0.1898 D(x): 0.0196 D(G(z)): 0.0246 / 0.0254
[32/32] Loss_D: 0.5213 Loss_G: 0.1982 D(x): 0.0111 D(G(z)): 0.0250 / 0.0246
-----THE [44/500] epoch end-----
-----THE [45/500] epoch start-----
[1/32] Loss_D: 0.5301 Loss_G: 0.2117 D(x): 0.0117 D(G(z)): 0.0248 / 0.0240
[2/32] Loss_D: 0.4245 Loss_G: 0.2001 D(x): 0.0164 D(G(z)): 0.0241 / 0.0240
[3/32] Loss_D: 0.3447 Loss_G: 0.1899 D(x): 0.0200 D(G(z)): 0.0235 / 0.0241
[4/32] Loss_D: 0.3756 Loss_G: 0.1867 D(x): 0.0187 D(G(z)): 0.0242 / 0.0247
[5/32] Loss_D: 0.5678 Loss_G: 0.1948 D(x): 0.0109 D(G(z)): 0.0246 / 0.0238
[6/32] Loss_D: 0.3868 Loss_G: 0.1932 D(x): 0.0188 D(G(z)): 0.0238 / 0.0240
[7/32] Loss_D: 0.5184 Loss_G: 0.1916 D(x): 0.0138 D(G(z)): 0.0247 / 0.0246
[8/32] Loss_D: 0.4546 Loss_G: 0.1930 D(x): 0.0147 D(G(z)): 0.0256 / 0.0254
[9/32] Loss_D: 0.4316 Loss_G

[18/32] Loss_D: 0.4040 Loss_G: 0.1951 D(x): 0.0178 D(G(z)): 0.0250 / 0.0253
tensor([0.4639, 0.4644, 0.4622, 0.4567, 0.4618, 0.4656, 0.4591, 0.4473, 0.4465,
        0.4610, 0.4684, 0.4617, 0.4663, 0.4624, 0.4458, 0.4601, 0.4521, 0.4614,
        0.4639, 0.4567], device='cuda:0', grad_fn=<PowBackward0>)
[19/32] Loss_D: 0.4868 Loss_G: 0.1942 D(x): 0.0143 D(G(z)): 0.0269 / 0.0262
tensor([0.4749, 0.4583, 0.4716, 0.4473, 0.4625, 0.4662, 0.4513, 0.4587, 0.4665,
        0.4675, 0.4564, 0.4575, 0.4574, 0.4543, 0.4527, 0.4590, 0.4668, 0.4648,
        0.4489, 0.4508], device='cuda:0', grad_fn=<PowBackward0>)
[20/32] Loss_D: 0.4531 Loss_G: 0.1939 D(x): 0.0152 D(G(z)): 0.0246 / 0.0245
tensor([0.4638, 0.4551, 0.3711, 0.4610, 0.4507, 0.4435, 0.4387, 0.4642, 0.4539,
        0.4465, 0.4485, 0.4604, 0.4552, 0.4403, 0.4598, 0.4814, 0.4515, 0.4602,
        0.4648, 0.4414], device='cuda:0', grad_fn=<PowBackward0>)
[21/32] Loss_D: 0.4599 Loss_G: 0.2024 D(x): 0.0143 D(G(z)): 0.0242 / 0.0239
tensor([0.4596, 0.

[21/32] Loss_D: 0.4456 Loss_G: 0.1948 D(x): 0.0152 D(G(z)): 0.0245 / 0.0240
[22/32] Loss_D: 0.4466 Loss_G: 0.1951 D(x): 0.0158 D(G(z)): 0.0244 / 0.0245
[23/32] Loss_D: 0.4346 Loss_G: 0.1925 D(x): 0.0163 D(G(z)): 0.0245 / 0.0245
[24/32] Loss_D: 0.4718 Loss_G: 0.1934 D(x): 0.0144 D(G(z)): 0.0246 / 0.0247
[25/32] Loss_D: 0.3187 Loss_G: 0.1860 D(x): 0.0217 D(G(z)): 0.0247 / 0.0255
[26/32] Loss_D: 0.5066 Loss_G: 0.1836 D(x): 0.0140 D(G(z)): 0.0264 / 0.0262
[27/32] Loss_D: 0.4675 Loss_G: 0.1839 D(x): 0.0158 D(G(z)): 0.0262 / 0.0257
[28/32] Loss_D: 0.4576 Loss_G: 0.1840 D(x): 0.0161 D(G(z)): 0.0257 / 0.0255
[29/32] Loss_D: 0.3562 Loss_G: 0.1877 D(x): 0.0200 D(G(z)): 0.0259 / 0.0252
[30/32] Loss_D: 0.4430 Loss_G: 0.1856 D(x): 0.0152 D(G(z)): 0.0254 / 0.0253
[31/32] Loss_D: 0.4027 Loss_G: 0.1898 D(x): 0.0179 D(G(z)): 0.0251 / 0.0249
[32/32] Loss_D: 0.4867 Loss_G: 0.1954 D(x): 0.0150 D(G(z)): 0.0252 / 0.0245
-----THE [48/500] epoch end-----
-----THE [49/500] epoch start-----
[1/32] Loss_D: 0.414

[8/32] Loss_D: 0.4777 Loss_G: 0.1996 D(x): 0.0145 D(G(z)): 0.0247 / 0.0247
tensor([0.4602, 0.4619, 0.4640, 0.4498, 0.4413, 0.4631, 0.4618, 0.4484, 0.4578,
        0.4492, 0.4577, 0.4497, 0.4441, 0.4532, 0.4675, 0.4589, 0.4593, 0.4526,
        0.4449, 0.4514], device='cuda:0', grad_fn=<PowBackward0>)
[9/32] Loss_D: 0.4253 Loss_G: 0.1982 D(x): 0.0168 D(G(z)): 0.0247 / 0.0246
tensor([0.4524, 0.4554, 0.4539, 0.4667, 0.4567, 0.4602, 0.4569, 0.4557, 0.4619,
        0.4586, 0.4567, 0.4538, 0.4537, 0.4441, 0.4410, 0.4610, 0.4366, 0.4518,
        0.4625, 0.4464], device='cuda:0', grad_fn=<PowBackward0>)
[10/32] Loss_D: 0.4520 Loss_G: 0.1987 D(x): 0.0162 D(G(z)): 0.0247 / 0.0245
tensor([0.4540, 0.4604, 0.4499, 0.4542, 0.4459, 0.4594, 0.4456, 0.4555, 0.4598,
        0.4604, 0.4511, 0.4520, 0.4631, 0.4523, 0.4542, 0.4520, 0.4676, 0.4587,
        0.4498, 0.4444], device='cuda:0', grad_fn=<PowBackward0>)
[11/32] Loss_D: 0.4033 Loss_G: 0.1985 D(x): 0.0171 D(G(z)): 0.0241 / 0.0240
tensor([0.4626, 0.46

[14/32] Loss_D: 0.3589 Loss_G: 0.1972 D(x): 0.0184 D(G(z)): 0.0247 / 0.0246
[15/32] Loss_D: 0.3500 Loss_G: 0.1885 D(x): 0.0196 D(G(z)): 0.0245 / 0.0247
[16/32] Loss_D: 0.4208 Loss_G: 0.1832 D(x): 0.0169 D(G(z)): 0.0248 / 0.0245
[17/32] Loss_D: 0.4786 Loss_G: 0.1846 D(x): 0.0146 D(G(z)): 0.0245 / 0.0242
[18/32] Loss_D: 0.4037 Loss_G: 0.1889 D(x): 0.0165 D(G(z)): 0.0242 / 0.0244
[19/32] Loss_D: 0.3733 Loss_G: 0.1826 D(x): 0.0191 D(G(z)): 0.0242 / 0.0247
[20/32] Loss_D: 0.4754 Loss_G: 0.1902 D(x): 0.0137 D(G(z)): 0.0257 / 0.0251
[21/32] Loss_D: 0.3879 Loss_G: 0.1919 D(x): 0.0178 D(G(z)): 0.0258 / 0.0251
[22/32] Loss_D: 0.4168 Loss_G: 0.1868 D(x): 0.0174 D(G(z)): 0.0243 / 0.0242
[23/32] Loss_D: 0.4223 Loss_G: 0.1879 D(x): 0.0155 D(G(z)): 0.0252 / 0.0248
[24/32] Loss_D: 0.4166 Loss_G: 0.1833 D(x): 0.0168 D(G(z)): 0.0245 / 0.0246
[25/32] Loss_D: 0.4206 Loss_G: 0.1793 D(x): 0.0165 D(G(z)): 0.0245 / 0.0247
[26/32] Loss_D: 0.4053 Loss_G: 0.1769 D(x): 0.0180 D(G(z)): 0.0253 / 0.0254
[27/32] Loss

[24/32] Loss_D: 0.5433 Loss_G: 0.1915 D(x): 0.0121 D(G(z)): 0.0254 / 0.0249
[25/32] Loss_D: 0.5302 Loss_G: 0.2076 D(x): 0.0122 D(G(z)): 0.0250 / 0.0243
[26/32] Loss_D: 0.4931 Loss_G: 0.2040 D(x): 0.0134 D(G(z)): 0.0235 / 0.0235
[27/32] Loss_D: 0.3635 Loss_G: 0.1892 D(x): 0.0193 D(G(z)): 0.0240 / 0.0245
[28/32] Loss_D: 0.4485 Loss_G: 0.1894 D(x): 0.0146 D(G(z)): 0.0245 / 0.0242
[29/32] Loss_D: 0.4354 Loss_G: 0.1943 D(x): 0.0154 D(G(z)): 0.0245 / 0.0242
[30/32] Loss_D: 0.4523 Loss_G: 0.1979 D(x): 0.0150 D(G(z)): 0.0243 / 0.0239
[31/32] Loss_D: 0.4048 Loss_G: 0.1890 D(x): 0.0175 D(G(z)): 0.0238 / 0.0241
[32/32] Loss_D: 0.4055 Loss_G: 0.1926 D(x): 0.0179 D(G(z)): 0.0229 / 0.0229
-----THE [55/500] epoch end-----
-----THE [56/500] epoch start-----
tensor([0.4589, 0.4774, 0.4780, 0.4790, 0.4706, 0.4457, 0.4684, 0.4771, 0.4713,
        0.4810, 0.4676, 0.4701, 0.4677, 0.4686, 0.4505, 0.4664, 0.4816, 0.4704,
        0.4658, 0.4609], device='cuda:0', grad_fn=<PowBackward0>)
[1/32] Loss_D: 0.4129 

[25/32] Loss_D: 0.4470 Loss_G: 0.1942 D(x): 0.0160 D(G(z)): 0.0239 / 0.0238
tensor([0.4664, 0.4733, 0.4581, 0.4631, 0.4503, 0.4714, 0.4601, 0.4494, 0.4657,
        0.4608, 0.4512, 0.4611, 0.4569, 0.4475, 0.4738, 0.4552, 0.4567, 0.4519,
        0.4845, 0.4656], device='cuda:0', grad_fn=<PowBackward0>)
[26/32] Loss_D: 0.4719 Loss_G: 0.1927 D(x): 0.0154 D(G(z)): 0.0249 / 0.0251
tensor([0.4588, 0.4492, 0.4832, 0.4804, 0.4647, 0.4804, 0.4556, 0.4431, 0.4531,
        0.4812, 0.4510, 0.4620, 0.4575, 0.4539, 0.4697, 0.4433, 0.4600, 0.4683,
        0.4837, 0.4626], device='cuda:0', grad_fn=<PowBackward0>)
[27/32] Loss_D: 0.4030 Loss_G: 0.1911 D(x): 0.0178 D(G(z)): 0.0248 / 0.0247
tensor([0.4649, 0.4569, 0.4879, 0.4579, 0.4416, 0.4652, 0.4590, 0.4576, 0.4649,
        0.4607, 0.4634, 0.4623, 0.4840, 0.4952, 0.4700, 0.4623, 0.4664, 0.4642,
        0.4616, 0.4565], device='cuda:0', grad_fn=<PowBackward0>)
[28/32] Loss_D: 0.3654 Loss_G: 0.1892 D(x): 0.0194 D(G(z)): 0.0254 / 0.0251
tensor([0.4546, 0.

[16/32] Loss_D: 0.3978 Loss_G: 0.1862 D(x): 0.0182 D(G(z)): 0.0250 / 0.0251
[17/32] Loss_D: 0.4345 Loss_G: 0.1874 D(x): 0.0166 D(G(z)): 0.0255 / 0.0254
[18/32] Loss_D: 0.4011 Loss_G: 0.1834 D(x): 0.0186 D(G(z)): 0.0254 / 0.0255
[19/32] Loss_D: 0.4399 Loss_G: 0.1871 D(x): 0.0156 D(G(z)): 0.0254 / 0.0250
[20/32] Loss_D: 0.4287 Loss_G: 0.1797 D(x): 0.0172 D(G(z)): 0.0260 / 0.0260
[21/32] Loss_D: 0.4651 Loss_G: 0.1876 D(x): 0.0152 D(G(z)): 0.0257 / 0.0253
[22/32] Loss_D: 0.4986 Loss_G: 0.1913 D(x): 0.0138 D(G(z)): 0.0260 / 0.0253
[23/32] Loss_D: 0.5095 Loss_G: 0.2027 D(x): 0.0125 D(G(z)): 0.0241 / 0.0237
[24/32] Loss_D: 0.3765 Loss_G: 0.1905 D(x): 0.0179 D(G(z)): 0.0242 / 0.0250
[25/32] Loss_D: 0.4690 Loss_G: 0.1902 D(x): 0.0149 D(G(z)): 0.0247 / 0.0246
[26/32] Loss_D: 0.3772 Loss_G: 0.1919 D(x): 0.0192 D(G(z)): 0.0243 / 0.0244
[27/32] Loss_D: 0.4006 Loss_G: 0.1894 D(x): 0.0176 D(G(z)): 0.0247 / 0.0247
[28/32] Loss_D: 0.4888 Loss_G: 0.1913 D(x): 0.0142 D(G(z)): 0.0256 / 0.0250
[29/32] Loss

[15/32] Loss_D: 0.4277 Loss_G: 0.1936 D(x): 0.0161 D(G(z)): 0.0242 / 0.0246
tensor([0.4823, 0.4645, 0.4526, 0.4809, 0.4479, 0.4906, 0.4479, 0.4549, 0.4756,
        0.4540, 0.4787, 0.4829, 0.4641, 0.4540, 0.4760, 0.4686, 0.4789, 0.4696,
        0.4403, 0.4703], device='cuda:0', grad_fn=<PowBackward0>)
[16/32] Loss_D: 0.4164 Loss_G: 0.1879 D(x): 0.0164 D(G(z)): 0.0248 / 0.0248
tensor([0.4835, 0.4492, 0.4906, 0.4264, 0.4624, 0.4558, 0.4631, 0.4799, 0.4785,
        0.4763, 0.4558, 0.4760, 0.4478, 0.4556, 0.4646, 0.4604, 0.4760, 0.4800,
        0.4677, 0.4627], device='cuda:0', grad_fn=<PowBackward0>)
[17/32] Loss_D: 0.4475 Loss_G: 0.1889 D(x): 0.0155 D(G(z)): 0.0255 / 0.0252
tensor([0.4407, 0.4845, 0.4449, 0.4802, 0.4824, 0.4771, 0.4317, 0.4860, 0.4507,
        0.4483, 0.4656, 0.4972, 0.4746, 0.4745, 0.4630, 0.4824, 0.4967, 0.4822,
        0.4797, 0.4778], device='cuda:0', grad_fn=<PowBackward0>)
[18/32] Loss_D: 0.4382 Loss_G: 0.1844 D(x): 0.0157 D(G(z)): 0.0247 / 0.0245
tensor([0.4771, 0.

[9/32] Loss_D: 0.4804 Loss_G: 0.1949 D(x): 0.0136 D(G(z)): 0.0247 / 0.0242
[10/32] Loss_D: 0.4917 Loss_G: 0.2027 D(x): 0.0138 D(G(z)): 0.0245 / 0.0239
[11/32] Loss_D: 0.3815 Loss_G: 0.1950 D(x): 0.0179 D(G(z)): 0.0236 / 0.0240
[12/32] Loss_D: 0.4378 Loss_G: 0.1907 D(x): 0.0158 D(G(z)): 0.0244 / 0.0240
[13/32] Loss_D: 0.4742 Loss_G: 0.1974 D(x): 0.0139 D(G(z)): 0.0244 / 0.0240
[14/32] Loss_D: 0.4196 Loss_G: 0.1933 D(x): 0.0166 D(G(z)): 0.0237 / 0.0240
[15/32] Loss_D: 0.4549 Loss_G: 0.1983 D(x): 0.0156 D(G(z)): 0.0242 / 0.0238
[16/32] Loss_D: 0.3782 Loss_G: 0.1969 D(x): 0.0183 D(G(z)): 0.0247 / 0.0239
[17/32] Loss_D: 0.4415 Loss_G: 0.1980 D(x): 0.0147 D(G(z)): 0.0237 / 0.0235
[18/32] Loss_D: 0.4074 Loss_G: 0.2025 D(x): 0.0164 D(G(z)): 0.0236 / 0.0235
[19/32] Loss_D: 0.4372 Loss_G: 0.2020 D(x): 0.0159 D(G(z)): 0.0239 / 0.0240
[20/32] Loss_D: 0.4449 Loss_G: 0.2064 D(x): 0.0157 D(G(z)): 0.0241 / 0.0232
[21/32] Loss_D: 0.5043 Loss_G: 0.2101 D(x): 0.0128 D(G(z)): 0.0233 / 0.0232
[22/32] Loss_

[5/32] Loss_D: 0.4139 Loss_G: 0.1816 D(x): 0.0164 D(G(z)): 0.0253 / 0.0253
tensor([0.4400, 0.4586, 0.4758, 0.4716, 0.4739, 0.4702, 0.4666, 0.4463, 0.4625,
        0.4565, 0.4656, 0.4645, 0.4708, 0.4693, 0.4654, 0.4705, 0.4688, 0.4484,
        0.4745, 0.4440], device='cuda:0', grad_fn=<PowBackward0>)
[6/32] Loss_D: 0.4681 Loss_G: 0.1909 D(x): 0.0139 D(G(z)): 0.0248 / 0.0242
tensor([0.4686, 0.4605, 0.4569, 0.4703, 0.4696, 0.4598, 0.4652, 0.4457, 0.4454,
        0.4662, 0.4643, 0.4675, 0.4573, 0.4633, 0.4453, 0.4507, 0.4315, 0.4501,
        0.4540, 0.4518], device='cuda:0', grad_fn=<PowBackward0>)
[7/32] Loss_D: 0.4788 Loss_G: 0.1962 D(x): 0.0138 D(G(z)): 0.0250 / 0.0248
tensor([0.4530, 0.4382, 0.4367, 0.4130, 0.4431, 0.4371, 0.4584, 0.4589, 0.4396,
        0.4403, 0.4352, 0.4166, 0.4537, 0.4447, 0.4112, 0.4590, 0.4237, 0.4340,
        0.4224, 0.4352], device='cuda:0', grad_fn=<PowBackward0>)
[8/32] Loss_D: 0.5264 Loss_G: 0.2139 D(x): 0.0114 D(G(z)): 0.0245 / 0.0236
tensor([0.4702, 0.4544

[2/32] Loss_D: 0.4053 Loss_G: 0.1913 D(x): 0.0161 D(G(z)): 0.0236 / 0.0239
[3/32] Loss_D: 0.4131 Loss_G: 0.1997 D(x): 0.0163 D(G(z)): 0.0246 / 0.0240
[4/32] Loss_D: 0.4994 Loss_G: 0.1905 D(x): 0.0128 D(G(z)): 0.0241 / 0.0243
[5/32] Loss_D: 0.4021 Loss_G: 0.1940 D(x): 0.0167 D(G(z)): 0.0243 / 0.0243
[6/32] Loss_D: 0.3996 Loss_G: 0.1826 D(x): 0.0174 D(G(z)): 0.0244 / 0.0243
[7/32] Loss_D: 0.4399 Loss_G: 0.1830 D(x): 0.0159 D(G(z)): 0.0246 / 0.0243
[8/32] Loss_D: 0.4331 Loss_G: 0.1871 D(x): 0.0163 D(G(z)): 0.0241 / 0.0239
[9/32] Loss_D: 0.4605 Loss_G: 0.1948 D(x): 0.0148 D(G(z)): 0.0247 / 0.0242
[10/32] Loss_D: 0.4475 Loss_G: 0.1881 D(x): 0.0164 D(G(z)): 0.0233 / 0.0232
[11/32] Loss_D: 0.4220 Loss_G: 0.1929 D(x): 0.0174 D(G(z)): 0.0234 / 0.0234
[12/32] Loss_D: 0.4639 Loss_G: 0.1941 D(x): 0.0151 D(G(z)): 0.0235 / 0.0231
[13/32] Loss_D: 0.3597 Loss_G: 0.1906 D(x): 0.0198 D(G(z)): 0.0240 / 0.0242
[14/32] Loss_D: 0.4447 Loss_G: 0.1892 D(x): 0.0146 D(G(z)): 0.0243 / 0.0243
[15/32] Loss_D: 0.50

[12/32] Loss_D: 0.4280 Loss_G: 0.1834 D(x): 0.0166 D(G(z)): 0.0256 / 0.0256
[13/32] Loss_D: 0.4968 Loss_G: 0.1987 D(x): 0.0131 D(G(z)): 0.0252 / 0.0248
[14/32] Loss_D: 0.4825 Loss_G: 0.1968 D(x): 0.0137 D(G(z)): 0.0241 / 0.0243
[15/32] Loss_D: 0.4725 Loss_G: 0.2017 D(x): 0.0141 D(G(z)): 0.0259 / 0.0253
[16/32] Loss_D: 0.3538 Loss_G: 0.1896 D(x): 0.0195 D(G(z)): 0.0245 / 0.0244
[17/32] Loss_D: 0.4268 Loss_G: 0.1876 D(x): 0.0152 D(G(z)): 0.0233 / 0.0235
[18/32] Loss_D: 0.4183 Loss_G: 0.1874 D(x): 0.0164 D(G(z)): 0.0244 / 0.0240
[19/32] Loss_D: 0.3551 Loss_G: 0.1786 D(x): 0.0190 D(G(z)): 0.0245 / 0.0250
[20/32] Loss_D: 0.4410 Loss_G: 0.1817 D(x): 0.0156 D(G(z)): 0.0236 / 0.0237
[21/32] Loss_D: 0.4292 Loss_G: 0.1759 D(x): 0.0168 D(G(z)): 0.0256 / 0.0257
[22/32] Loss_D: 0.3724 Loss_G: 0.1782 D(x): 0.0181 D(G(z)): 0.0252 / 0.0249
[23/32] Loss_D: 0.3960 Loss_G: 0.1723 D(x): 0.0183 D(G(z)): 0.0247 / 0.0250
[24/32] Loss_D: 0.3622 Loss_G: 0.1699 D(x): 0.0190 D(G(z)): 0.0259 / 0.0260
[25/32] Loss

[22/32] Loss_D: 0.4223 Loss_G: 0.1835 D(x): 0.0158 D(G(z)): 0.0257 / 0.0252
tensor([0.4559, 0.4663, 0.4568, 0.4538, 0.4729, 0.4626, 0.4718, 0.4502, 0.4584,
        0.4572, 0.4695, 0.4654, 0.4558, 0.4661, 0.4635, 0.4621, 0.4783, 0.4657,
        0.4603, 0.4668], device='cuda:0', grad_fn=<PowBackward0>)
[23/32] Loss_D: 0.4692 Loss_G: 0.1911 D(x): 0.0141 D(G(z)): 0.0252 / 0.0245
tensor([0.4837, 0.4610, 0.4805, 0.4841, 0.4741, 0.4725, 0.4684, 0.4975, 0.4947,
        0.4790, 0.4716, 0.4732, 0.4797, 0.4600, 0.4776, 0.4901, 0.4752, 0.4658,
        0.4735, 0.4735], device='cuda:0', grad_fn=<PowBackward0>)
[24/32] Loss_D: 0.3804 Loss_G: 0.1792 D(x): 0.0182 D(G(z)): 0.0243 / 0.0251
tensor([0.4937, 0.4752, 0.4789, 0.4716, 0.4635, 0.4782, 0.4620, 0.4859, 0.4870,
        0.4642, 0.4710, 0.4801, 0.4862, 0.4689, 0.4659, 0.4802, 0.4909, 0.4881,
        0.4854, 0.4740], device='cuda:0', grad_fn=<PowBackward0>)
[25/32] Loss_D: 0.4634 Loss_G: 0.1786 D(x): 0.0145 D(G(z)): 0.0253 / 0.0253
tensor([0.4689, 0.

[4/32] Loss_D: 0.4347 Loss_G: 0.1843 D(x): 0.0160 D(G(z)): 0.0243 / 0.0240
[5/32] Loss_D: 0.4491 Loss_G: 0.1907 D(x): 0.0148 D(G(z)): 0.0254 / 0.0246
[6/32] Loss_D: 0.3769 Loss_G: 0.1837 D(x): 0.0181 D(G(z)): 0.0230 / 0.0233
[7/32] Loss_D: 0.4656 Loss_G: 0.1902 D(x): 0.0146 D(G(z)): 0.0246 / 0.0240
[8/32] Loss_D: 0.3748 Loss_G: 0.1822 D(x): 0.0184 D(G(z)): 0.0241 / 0.0245
[9/32] Loss_D: 0.4141 Loss_G: 0.1794 D(x): 0.0177 D(G(z)): 0.0246 / 0.0247
[10/32] Loss_D: 0.4092 Loss_G: 0.1801 D(x): 0.0172 D(G(z)): 0.0247 / 0.0247
[11/32] Loss_D: 0.3793 Loss_G: 0.1738 D(x): 0.0185 D(G(z)): 0.0252 / 0.0249
[12/32] Loss_D: 0.4452 Loss_G: 0.1761 D(x): 0.0153 D(G(z)): 0.0244 / 0.0238
[13/32] Loss_D: 0.4270 Loss_G: 0.1781 D(x): 0.0163 D(G(z)): 0.0246 / 0.0249
[14/32] Loss_D: 0.4175 Loss_G: 0.1757 D(x): 0.0165 D(G(z)): 0.0255 / 0.0255
[15/32] Loss_D: 0.3927 Loss_G: 0.1735 D(x): 0.0181 D(G(z)): 0.0249 / 0.0249
[16/32] Loss_D: 0.4054 Loss_G: 0.1774 D(x): 0.0170 D(G(z)): 0.0249 / 0.0246
[17/32] Loss_D: 0.

[12/32] Loss_D: 0.4860 Loss_G: 0.1803 D(x): 0.0149 D(G(z)): 0.0249 / 0.0246
tensor([0.4532, 0.4655, 0.4836, 0.4725, 0.4773, 0.4651, 0.4863, 0.4793, 0.4838,
        0.4756, 0.4896, 0.4543, 0.4869, 0.4727, 0.4728, 0.4768, 0.4733, 0.5048,
        0.4632, 0.4601], device='cuda:0', grad_fn=<PowBackward0>)
[13/32] Loss_D: 0.4009 Loss_G: 0.1809 D(x): 0.0166 D(G(z)): 0.0249 / 0.0247
tensor([0.4782, 0.4852, 0.4655, 0.4716, 0.4649, 0.4532, 0.4579, 0.4684, 0.4736,
        0.4562, 0.4796, 0.4619, 0.4632, 0.4744, 0.4609, 0.4727, 0.4616, 0.4706,
        0.4554, 0.4592], device='cuda:0', grad_fn=<PowBackward0>)
[14/32] Loss_D: 0.4326 Loss_G: 0.1878 D(x): 0.0164 D(G(z)): 0.0245 / 0.0243
tensor([0.4584, 0.4581, 0.4873, 0.4684, 0.4864, 0.4581, 0.4768, 0.4627, 0.4658,
        0.4621, 0.4726, 0.4635, 0.4807, 0.4629, 0.4633, 0.4951, 0.4672, 0.4744,
        0.4695, 0.4641], device='cuda:0', grad_fn=<PowBackward0>)
[15/32] Loss_D: 0.3742 Loss_G: 0.1851 D(x): 0.0185 D(G(z)): 0.0245 / 0.0249
tensor([0.4598, 0.

[30/32] Loss_D: 0.3699 Loss_G: 0.1714 D(x): 0.0185 D(G(z)): 0.0243 / 0.0244
[31/32] Loss_D: 0.3917 Loss_G: 0.1753 D(x): 0.0175 D(G(z)): 0.0245 / 0.0243
[32/32] Loss_D: 0.5404 Loss_G: 0.1940 D(x): 0.0117 D(G(z)): 0.0244 / 0.0227
-----THE [77/500] epoch end-----
-----THE [78/500] epoch start-----
[1/32] Loss_D: 0.4432 Loss_G: 0.1856 D(x): 0.0156 D(G(z)): 0.0235 / 0.0239
[2/32] Loss_D: 0.4850 Loss_G: 0.1930 D(x): 0.0132 D(G(z)): 0.0247 / 0.0243
[3/32] Loss_D: 0.4166 Loss_G: 0.1822 D(x): 0.0166 D(G(z)): 0.0235 / 0.0235
[4/32] Loss_D: 0.4463 Loss_G: 0.1790 D(x): 0.0151 D(G(z)): 0.0240 / 0.0241
[5/32] Loss_D: 0.4116 Loss_G: 0.1749 D(x): 0.0165 D(G(z)): 0.0239 / 0.0239
[6/32] Loss_D: 0.4861 Loss_G: 0.1823 D(x): 0.0141 D(G(z)): 0.0242 / 0.0241
[7/32] Loss_D: 0.4688 Loss_G: 0.1774 D(x): 0.0135 D(G(z)): 0.0241 / 0.0242
[8/32] Loss_D: 0.4196 Loss_G: 0.1743 D(x): 0.0168 D(G(z)): 0.0243 / 0.0249
[9/32] Loss_D: 0.3882 Loss_G: 0.1698 D(x): 0.0190 D(G(z)): 0.0248 / 0.0251
[10/32] Loss_D: 0.4476 Loss_G

[2/32] Loss_D: 0.4801 Loss_G: 0.1908 D(x): 0.0145 D(G(z)): 0.0246 / 0.0248
tensor([0.4667, 0.4750, 0.4678, 0.4689, 0.4693, 0.4657, 0.4670, 0.4763, 0.4687,
        0.4753, 0.4681, 0.4828, 0.4731, 0.4632, 0.4623, 0.4628, 0.4846, 0.4808,
        0.4691, 0.4703], device='cuda:0', grad_fn=<PowBackward0>)
[3/32] Loss_D: 0.4407 Loss_G: 0.1842 D(x): 0.0159 D(G(z)): 0.0238 / 0.0241
tensor([0.4658, 0.4612, 0.4814, 0.4759, 0.4655, 0.4566, 0.4678, 0.4599, 0.4548,
        0.4709, 0.4686, 0.4641, 0.4764, 0.4789, 0.4726, 0.4727, 0.4728, 0.4690,
        0.4869, 0.4627], device='cuda:0', grad_fn=<PowBackward0>)
[4/32] Loss_D: 0.4602 Loss_G: 0.1856 D(x): 0.0151 D(G(z)): 0.0237 / 0.0233
tensor([0.4887, 0.4807, 0.4851, 0.4743, 0.4792, 0.4663, 0.4716, 0.4996, 0.4877,
        0.4720, 0.4808, 0.4811, 0.4688, 0.4745, 0.4675, 0.4708, 0.4722, 0.4899,
        0.4762, 0.4939], device='cuda:0', grad_fn=<PowBackward0>)
[5/32] Loss_D: 0.4089 Loss_G: 0.1773 D(x): 0.0168 D(G(z)): 0.0258 / 0.0256
tensor([0.4739, 0.4643

tensor([0.4909, 0.4919, 0.4847, 0.4972, 0.4876, 0.5052, 0.4901, 0.4729, 0.4940,
        0.4766, 0.4902, 0.4966, 0.4819, 0.4918, 0.4672, 0.4916, 0.4764, 0.5036,
        0.4953, 0.4889], device='cuda:0', grad_fn=<PowBackward0>)
[30/32] Loss_D: 0.4329 Loss_G: 0.1692 D(x): 0.0156 D(G(z)): 0.0256 / 0.0256
tensor([0.4772, 0.4745, 0.4876, 0.4909, 0.4659, 0.4831, 0.4645, 0.4589, 0.4838,
        0.4711, 0.4881, 0.4633, 0.4891, 0.4832, 0.5081, 0.4792, 0.4770, 0.4831,
        0.4615, 0.4903], device='cuda:0', grad_fn=<PowBackward0>)
[31/32] Loss_D: 0.4423 Loss_G: 0.1774 D(x): 0.0151 D(G(z)): 0.0245 / 0.0242
tensor([0.4363, 0.4626, 0.4801, 0.4565], device='cuda:0',
       grad_fn=<PowBackward0>)
[32/32] Loss_D: 0.5264 Loss_G: 0.1948 D(x): 0.0115 D(G(z)): 0.0255 / 0.0242
-----THE [81/500] epoch end-----
-----THE [82/500] epoch start-----
[1/32] Loss_D: 0.4349 Loss_G: 0.1967 D(x): 0.0150 D(G(z)): 0.0234 / 0.0232
[2/32] Loss_D: 0.4515 Loss_G: 0.1874 D(x): 0.0154 D(G(z)): 0.0244 / 0.0245
[3/32] Loss_D

[1/32] Loss_D: 0.3822 Loss_G: 0.1723 D(x): 0.0182 D(G(z)): 0.0246 / 0.0251
[2/32] Loss_D: 0.4736 Loss_G: 0.1863 D(x): 0.0137 D(G(z)): 0.0253 / 0.0242
[3/32] Loss_D: 0.3809 Loss_G: 0.1735 D(x): 0.0185 D(G(z)): 0.0246 / 0.0252
[4/32] Loss_D: 0.4619 Loss_G: 0.1741 D(x): 0.0148 D(G(z)): 0.0249 / 0.0250
[5/32] Loss_D: 0.3907 Loss_G: 0.1744 D(x): 0.0174 D(G(z)): 0.0253 / 0.0251
[6/32] Loss_D: 0.4507 Loss_G: 0.1751 D(x): 0.0159 D(G(z)): 0.0255 / 0.0253
[7/32] Loss_D: 0.3540 Loss_G: 0.1678 D(x): 0.0193 D(G(z)): 0.0244 / 0.0249
[8/32] Loss_D: 0.4086 Loss_G: 0.1677 D(x): 0.0181 D(G(z)): 0.0249 / 0.0248
[9/32] Loss_D: 0.4447 Loss_G: 0.1692 D(x): 0.0155 D(G(z)): 0.0250 / 0.0250
[10/32] Loss_D: 0.4036 Loss_G: 0.1694 D(x): 0.0180 D(G(z)): 0.0249 / 0.0247
[11/32] Loss_D: 0.4215 Loss_G: 0.1751 D(x): 0.0156 D(G(z)): 0.0254 / 0.0248
[12/32] Loss_D: 0.3583 Loss_G: 0.1667 D(x): 0.0197 D(G(z)): 0.0242 / 0.0248
[13/32] Loss_D: 0.4613 Loss_G: 0.1741 D(x): 0.0152 D(G(z)): 0.0252 / 0.0252
[14/32] Loss_D: 0.453

tensor([0.4803, 0.4794, 0.4738, 0.4841, 0.4870, 0.4902, 0.4763, 0.4674, 0.4797,
        0.4754, 0.4875, 0.4764, 0.4795, 0.4713, 0.4791, 0.4808, 0.4781, 0.4739,
        0.4861, 0.4768], device='cuda:0', grad_fn=<PowBackward0>)
[20/32] Loss_D: 0.4140 Loss_G: 0.1771 D(x): 0.0163 D(G(z)): 0.0244 / 0.0245
tensor([0.4597, 0.4746, 0.4838, 0.4810, 0.4958, 0.4852, 0.4834, 0.4897, 0.4738,
        0.4819, 0.4765, 0.4831, 0.4732, 0.4869, 0.4642, 0.4804, 0.4810, 0.4837,
        0.4808, 0.4634], device='cuda:0', grad_fn=<PowBackward0>)
[21/32] Loss_D: 0.4633 Loss_G: 0.1772 D(x): 0.0150 D(G(z)): 0.0240 / 0.0240
tensor([0.4877, 0.4784, 0.4783, 0.4889, 0.4789, 0.4697, 0.4819, 0.4804, 0.4835,
        0.4791, 0.4664, 0.4767, 0.4807, 0.4828, 0.4813, 0.4901, 0.4779, 0.4707,
        0.4808, 0.4947], device='cuda:0', grad_fn=<PowBackward0>)
[22/32] Loss_D: 0.4479 Loss_G: 0.1761 D(x): 0.0152 D(G(z)): 0.0240 / 0.0238
tensor([0.4691, 0.4790, 0.4658, 0.4766, 0.4729, 0.4682, 0.4626, 0.5065, 0.4631,
        0.4593

[26/32] Loss_D: 0.3915 Loss_G: 0.1646 D(x): 0.0183 D(G(z)): 0.0246 / 0.0249
[27/32] Loss_D: 0.3910 Loss_G: 0.1644 D(x): 0.0178 D(G(z)): 0.0255 / 0.0255
[28/32] Loss_D: 0.4007 Loss_G: 0.1677 D(x): 0.0189 D(G(z)): 0.0255 / 0.0256
[29/32] Loss_D: 0.4449 Loss_G: 0.1693 D(x): 0.0165 D(G(z)): 0.0260 / 0.0254
[30/32] Loss_D: 0.4412 Loss_G: 0.1725 D(x): 0.0160 D(G(z)): 0.0258 / 0.0253
[31/32] Loss_D: 0.4914 Loss_G: 0.1751 D(x): 0.0129 D(G(z)): 0.0257 / 0.0249
[32/32] Loss_D: 0.4451 Loss_G: 0.2152 D(x): 0.0175 D(G(z)): 0.0238 / 0.0212
-----THE [88/500] epoch end-----
-----THE [89/500] epoch start-----
[1/32] Loss_D: 0.4001 Loss_G: 0.2149 D(x): 0.0160 D(G(z)): 0.0215 / 0.0218
[2/32] Loss_D: 0.4609 Loss_G: 0.1921 D(x): 0.0139 D(G(z)): 0.0221 / 0.0235
[3/32] Loss_D: 0.5159 Loss_G: 0.1907 D(x): 0.0124 D(G(z)): 0.0238 / 0.0238
[4/32] Loss_D: 0.3737 Loss_G: 0.1789 D(x): 0.0179 D(G(z)): 0.0245 / 0.0246
[5/32] Loss_D: 0.4444 Loss_G: 0.1824 D(x): 0.0148 D(G(z)): 0.0245 / 0.0245
[6/32] Loss_D: 0.4057 Los

[9/32] Loss_D: 0.4291 Loss_G: 0.1750 D(x): 0.0161 D(G(z)): 0.0252 / 0.0251
tensor([0.4758, 0.4863, 0.4921, 0.4876, 0.4986, 0.4848, 0.4870, 0.5087, 0.4945,
        0.4877, 0.4960, 0.4767, 0.4822, 0.4841, 0.4958, 0.4822, 0.4901, 0.4837,
        0.4856, 0.4937], device='cuda:0', grad_fn=<PowBackward0>)
[10/32] Loss_D: 0.4253 Loss_G: 0.1693 D(x): 0.0169 D(G(z)): 0.0250 / 0.0251
tensor([0.5047, 0.4764, 0.4813, 0.4894, 0.4742, 0.4773, 0.4572, 0.4920, 0.4914,
        0.4910, 0.4639, 0.4977, 0.4877, 0.5020, 0.4918, 0.4966, 0.4773, 0.4909,
        0.4965, 0.4753], device='cuda:0', grad_fn=<PowBackward0>)
[11/32] Loss_D: 0.4454 Loss_G: 0.1718 D(x): 0.0149 D(G(z)): 0.0247 / 0.0245
tensor([0.4962, 0.4816, 0.4942, 0.4896, 0.4773, 0.4722, 0.4858, 0.4947, 0.5181,
        0.5192, 0.4805, 0.4846, 0.4783, 0.4968, 0.4680, 0.4954, 0.4793, 0.4897,
        0.4851, 0.4784], device='cuda:0', grad_fn=<PowBackward0>)
[12/32] Loss_D: 0.4412 Loss_G: 0.1697 D(x): 0.0160 D(G(z)): 0.0247 / 0.0248
tensor([0.4750, 0.4

[18/32] Loss_D: 0.4648 Loss_G: 0.1715 D(x): 0.0157 D(G(z)): 0.0246 / 0.0242
[19/32] Loss_D: 0.4377 Loss_G: 0.1728 D(x): 0.0160 D(G(z)): 0.0251 / 0.0252
[20/32] Loss_D: 0.4258 Loss_G: 0.1752 D(x): 0.0162 D(G(z)): 0.0246 / 0.0241
[21/32] Loss_D: 0.3605 Loss_G: 0.1719 D(x): 0.0190 D(G(z)): 0.0237 / 0.0241
[22/32] Loss_D: 0.3619 Loss_G: 0.1673 D(x): 0.0189 D(G(z)): 0.0250 / 0.0251
[23/32] Loss_D: 0.4511 Loss_G: 0.1672 D(x): 0.0164 D(G(z)): 0.0256 / 0.0254
[24/32] Loss_D: 0.3851 Loss_G: 0.1701 D(x): 0.0187 D(G(z)): 0.0262 / 0.0257
[25/32] Loss_D: 0.3665 Loss_G: 0.1667 D(x): 0.0186 D(G(z)): 0.0248 / 0.0247
[26/32] Loss_D: 0.4905 Loss_G: 0.1721 D(x): 0.0145 D(G(z)): 0.0246 / 0.0246
[27/32] Loss_D: 0.3524 Loss_G: 0.1684 D(x): 0.0187 D(G(z)): 0.0239 / 0.0241
[28/32] Loss_D: 0.3550 Loss_G: 0.1594 D(x): 0.0199 D(G(z)): 0.0253 / 0.0254
[29/32] Loss_D: 0.4137 Loss_G: 0.1681 D(x): 0.0180 D(G(z)): 0.0258 / 0.0254
[30/32] Loss_D: 0.4195 Loss_G: 0.1745 D(x): 0.0160 D(G(z)): 0.0249 / 0.0244
[31/32] Loss

[28/32] Loss_D: 0.5143 Loss_G: 0.1688 D(x): 0.0135 D(G(z)): 0.0257 / 0.0252
[29/32] Loss_D: 0.4162 Loss_G: 0.1714 D(x): 0.0163 D(G(z)): 0.0250 / 0.0251
[30/32] Loss_D: 0.3962 Loss_G: 0.1666 D(x): 0.0182 D(G(z)): 0.0257 / 0.0258
[31/32] Loss_D: 0.4130 Loss_G: 0.1620 D(x): 0.0179 D(G(z)): 0.0260 / 0.0262
[32/32] Loss_D: 0.4279 Loss_G: 0.1718 D(x): 0.0158 D(G(z)): 0.0255 / 0.0252
-----THE [95/500] epoch end-----
-----THE [96/500] epoch start-----
tensor([0.4917, 0.4920, 0.4884, 0.4860, 0.5032, 0.4779, 0.4696, 0.4961, 0.4673,
        0.4942, 0.4874, 0.4922, 0.4750, 0.4850, 0.4852, 0.4824, 0.4840, 0.4981,
        0.4952, 0.4908], device='cuda:0', grad_fn=<PowBackward0>)
[1/32] Loss_D: 0.4164 Loss_G: 0.1706 D(x): 0.0168 D(G(z)): 0.0254 / 0.0252
tensor([0.4520, 0.4554, 0.4899, 0.4978, 0.4694, 0.4970, 0.4498, 0.4837, 0.5037,
        0.4793, 0.4761, 0.4657, 0.4433, 0.4575, 0.4974, 0.4458, 0.4485, 0.4757,
        0.4457, 0.4812], device='cuda:0', grad_fn=<PowBackward0>)
[2/32] Loss_D: 0.4198 Los

[26/32] Loss_D: 0.4432 Loss_G: 0.1734 D(x): 0.0153 D(G(z)): 0.0261 / 0.0256
tensor([0.4855, 0.4956, 0.5061, 0.4835, 0.4946, 0.4805, 0.4789, 0.4868, 0.5153,
        0.5012, 0.4683, 0.4865, 0.5013, 0.4781, 0.4956, 0.4828, 0.4876, 0.4917,
        0.4897, 0.5043], device='cuda:0', grad_fn=<PowBackward0>)
[27/32] Loss_D: 0.3262 Loss_G: 0.1677 D(x): 0.0211 D(G(z)): 0.0243 / 0.0241
tensor([0.4889, 0.4950, 0.4918, 0.4929, 0.4888, 0.4864, 0.4835, 0.4908, 0.4939,
        0.5022, 0.4848, 0.4952, 0.4871, 0.4977, 0.4973, 0.4848, 0.5150, 0.4991,
        0.4900, 0.5051], device='cuda:0', grad_fn=<PowBackward0>)
[28/32] Loss_D: 0.4685 Loss_G: 0.1653 D(x): 0.0145 D(G(z)): 0.0251 / 0.0259
tensor([0.4877, 0.4871, 0.4796, 0.5033, 0.4895, 0.4876, 0.4817, 0.4949, 0.4903,
        0.4905, 0.5048, 0.5031, 0.4839, 0.4918, 0.4877, 0.4978, 0.4918, 0.5015,
        0.4800, 0.4962], device='cuda:0', grad_fn=<PowBackward0>)
[29/32] Loss_D: 0.3960 Loss_G: 0.1669 D(x): 0.0179 D(G(z)): 0.0245 / 0.0246
tensor([0.4946, 0.

[20/32] Loss_D: 0.4469 Loss_G: 0.1685 D(x): 0.0163 D(G(z)): 0.0248 / 0.0249
[21/32] Loss_D: 0.3990 Loss_G: 0.1673 D(x): 0.0192 D(G(z)): 0.0251 / 0.0248
[22/32] Loss_D: 0.3892 Loss_G: 0.1628 D(x): 0.0186 D(G(z)): 0.0253 / 0.0259
[23/32] Loss_D: 0.4786 Loss_G: 0.1751 D(x): 0.0150 D(G(z)): 0.0257 / 0.0250
[24/32] Loss_D: 0.4251 Loss_G: 0.1772 D(x): 0.0160 D(G(z)): 0.0253 / 0.0245
[25/32] Loss_D: 0.4754 Loss_G: 0.1724 D(x): 0.0139 D(G(z)): 0.0244 / 0.0245
[26/32] Loss_D: 0.4122 Loss_G: 0.1662 D(x): 0.0176 D(G(z)): 0.0250 / 0.0253
[27/32] Loss_D: 0.4557 Loss_G: 0.1747 D(x): 0.0156 D(G(z)): 0.0254 / 0.0250
[28/32] Loss_D: 0.4362 Loss_G: 0.1690 D(x): 0.0155 D(G(z)): 0.0258 / 0.0255
[29/32] Loss_D: 0.4377 Loss_G: 0.1696 D(x): 0.0151 D(G(z)): 0.0242 / 0.0241
[30/32] Loss_D: 0.3782 Loss_G: 0.1687 D(x): 0.0180 D(G(z)): 0.0252 / 0.0253
[31/32] Loss_D: 0.3856 Loss_G: 0.1664 D(x): 0.0177 D(G(z)): 0.0253 / 0.0251
[32/32] Loss_D: 0.2960 Loss_G: 0.1650 D(x): 0.0219 D(G(z)): 0.0245 / 0.0240
-----THE [99

[16/32] Loss_D: 0.4299 Loss_G: 0.1731 D(x): 0.0169 D(G(z)): 0.0245 / 0.0247
tensor([0.4927, 0.4880, 0.4871, 0.4969, 0.4935, 0.4831, 0.4969, 0.4909, 0.4989,
        0.5021, 0.4983, 0.5027, 0.4824, 0.4909, 0.4827, 0.4967, 0.4853, 0.4904,
        0.4837, 0.4952], device='cuda:0', grad_fn=<PowBackward0>)
[17/32] Loss_D: 0.3840 Loss_G: 0.1666 D(x): 0.0181 D(G(z)): 0.0247 / 0.0248
tensor([0.4985, 0.4887, 0.4962, 0.4855, 0.4925, 0.4938, 0.4687, 0.4882, 0.4688,
        0.4912, 0.4916, 0.5025, 0.4920, 0.4906, 0.4966, 0.4877, 0.5005, 0.4937,
        0.4897, 0.4830], device='cuda:0', grad_fn=<PowBackward0>)
[18/32] Loss_D: 0.3734 Loss_G: 0.1682 D(x): 0.0180 D(G(z)): 0.0255 / 0.0251
tensor([0.4835, 0.4837, 0.4876, 0.4687, 0.4748, 0.4892, 0.4785, 0.4921, 0.4974,
        0.4900, 0.4888, 0.4869, 0.4687, 0.4767, 0.4916, 0.4849, 0.4769, 0.4922,
        0.4961, 0.4945], device='cuda:0', grad_fn=<PowBackward0>)
[19/32] Loss_D: 0.5123 Loss_G: 0.1722 D(x): 0.0131 D(G(z)): 0.0251 / 0.0248
tensor([0.4832, 0.

KeyboardInterrupt: 